import { MountainIcon } from '@serwis-bielecki-public/components/icons';
import { Button } from '@serwis-bielecki-public/components/ui/button';
import { Inter } from 'next/font/google';
import { cn } from '@serwis-bielecki-public/components/utils';
import './global.css';
import Link from 'next/link';

export const metadata = {
  title: 'Welcome to junkers',
  description: 'Generated by create-nx-workspace',
};

const fontHeading = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
});

const fontBody = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-body',
});

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={cn('antialiased', fontHeading.variable, fontBody.variable)}
      >
        <div className="flex min-h-[100dvh] flex-col">
          <header className="sticky top-0 z-50 bg-background">
            <div className="container mx-auto flex h-16 items-center justify-between px-4 md:px-6">
              <Link
                href="#"
                className="flex items-center gap-2"
                prefetch={false}
              >
                <MountainIcon className="h-6 w-6" />
                <span className="text-lg font-bold">Junkers Bielecki</span>
              </Link>
              <nav className="hidden space-x-4 md:flex">
                <Link
                  href="#"
                  className="text-sm font-medium hover:underline underline-offset-4"
                  prefetch={false}
                >
                  Home
                </Link>
                <Link
                  href="#"
                  className="text-sm font-medium hover:underline underline-offset-4"
                  prefetch={false}
                >
                  Services
                </Link>
                <Link
                  href="#"
                  className="text-sm font-medium hover:underline underline-offset-4"
                  prefetch={false}
                >
                  Products
                </Link>
                <Link
                  href="#"
                  className="text-sm font-medium hover:underline underline-offset-4"
                  prefetch={false}
                >
                  About
                </Link>
                <Link
                  href="#"
                  className="text-sm font-medium hover:underline underline-offset-4"
                  prefetch={false}
                >
                  Contact
                </Link>
              </nav>
              <Button>Get a Quote</Button>
            </div>
          </header>
          <main className="flex-1">{children}</main>
          <footer className="bg-muted p-6 md:py-12 w-full">
            <div className="container mx-auto max-w-7xl grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-8 text-sm">
              <div className="grid gap-1">
                <h3 className="font-semibold">Company</h3>
                <Link href="#" prefetch={false}>
                  About Us
                </Link>
                <Link href="#" prefetch={false}>
                  Our Team
                </Link>
                <Link href="#" prefetch={false}>
                  Careers
                </Link>
                <Link href="#" prefetch={false}>
                  News
                </Link>
              </div>
              <div className="grid gap-1">
                <h3 className="font-semibold">Products</h3>
                <Link href="#" prefetch={false}>
                  Industrial Equipment
                </Link>
                <Link href="#" prefetch={false}>
                  Automation Solutions
                </Link>
                <Link href="#" prefetch={false}>
                  Customized Solutions
                </Link>
              </div>
              <div className="grid gap-1">
                <h3 className="font-semibold">Services</h3>
                <Link href="#" prefetch={false}>
                  Installation
                </Link>
                <Link href="#" prefetch={false}>
                  Maintenance
                </Link>
                <Link href="#" prefetch={false}>
                  Consulting
                </Link>
              </div>
              <div className="grid gap-1">
                <h3 className="font-semibold">Legal</h3>
                <Link href="#" prefetch={false}>
                  Privacy Policy
                </Link>
                <Link href="#" prefetch={false}>
                  Terms of Service
                </Link>
                <Link href="#" prefetch={false}>
                  Cookie Policy
                </Link>
              </div>
              <div className="grid gap-1">
                <h3 className="font-semibold">Connect</h3>
                <Link href="#" prefetch={false}>
                  Facebook
                </Link>
                <Link href="#" prefetch={false}>
                  Twitter
                </Link>
                <Link href="#" prefetch={false}>
                  LinkedIn
                </Link>
                <Link href="#" prefetch={false}>
                  Instagram
                </Link>
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
