import { Inter } from 'next/font/google'
import { cn } from '@serwis-bielecki-public/components/utils'
import './global.css'

export const metadata = {
  title: 'Welcome to junkers',
  description: 'Generated by create-nx-workspace',
};

const fontHeading = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
})

const fontBody = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-body',
})

export default function Layout({ children }: { children: React.ReactNode; }) {
  return (
    <html lang="en">
    <body
      className={cn(
        'antialiased',
        fontHeading.variable,
        fontBody.variable,
      )}
    >
    {children}
    </body>
    </html>
  )
}
