name: Pages
concurrency:
  group: pages
  cancel-in-progress: false
on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'Git sha to checkout and publish'
        required: true
        type: string
        default: 'main'
      company:
        description: 'Company to deploy'
        required: true
        default: 'Junkers'
        type: choice
        options:
          - Junkers
          - Buderus
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  main:
    name: Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.sha }}
      - name: Setup
        uses: ./.github/actions/setup
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Next.js
        run: npx nx run web:export
        env:
          BASE_PATH: ${{ steps.pages.outputs.base_path }}
          COMPANY: ${{ github.event.inputs.company }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./apps/web/out
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
